/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    roles: Role;
    categories: Category;
    subcategories: Subcategory;
    units: Unit;
    'unit-equivalences': UnitEquivalence;
    warehouses: Warehouse;
    sections: Section;
    racks: Rack;
    products: Product;
    'stock-levels': StockLevel;
    'stock-lots': StockLot;
    'stock-movements': StockMovement;
    'kardex-entries': KardexEntry;
    suppliers: Supplier;
    customers: Customer;
    'purchase-orders': PurchaseOrder;
    'sales-orders': SalesOrder;
    'audit-logs': AuditLog;
    returns: Return;
    notifications: Notification;
    settings: Setting;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    subcategories: SubcategoriesSelect<false> | SubcategoriesSelect<true>;
    units: UnitsSelect<false> | UnitsSelect<true>;
    'unit-equivalences': UnitEquivalencesSelect<false> | UnitEquivalencesSelect<true>;
    warehouses: WarehousesSelect<false> | WarehousesSelect<true>;
    sections: SectionsSelect<false> | SectionsSelect<true>;
    racks: RacksSelect<false> | RacksSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'stock-levels': StockLevelsSelect<false> | StockLevelsSelect<true>;
    'stock-lots': StockLotsSelect<false> | StockLotsSelect<true>;
    'stock-movements': StockMovementsSelect<false> | StockMovementsSelect<true>;
    'kardex-entries': KardexEntriesSelect<false> | KardexEntriesSelect<true>;
    suppliers: SuppliersSelect<false> | SuppliersSelect<true>;
    customers: CustomersSelect<false> | CustomersSelect<true>;
    'purchase-orders': PurchaseOrdersSelect<false> | PurchaseOrdersSelect<true>;
    'sales-orders': SalesOrdersSelect<false> | SalesOrdersSelect<true>;
    'audit-logs': AuditLogsSelect<false> | AuditLogsSelect<true>;
    returns: ReturnsSelect<false> | ReturnsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  /**
   * Roles legacy (guest, seller, operator, viewer) se conservan en usuarios existentes; asignar solo los cinco roles canónicos.
   */
  roles: ('admin' | 'supervisor' | 'warehouse' | 'client' | 'invitado' | 'guest' | 'seller' | 'operator' | 'viewer')[];
  fullName?: string | null;
  status: 'active' | 'inactive' | 'locked';
  lastLoginAt?: string | null;
  /**
   * Vincula este usuario con su ficha de cliente (rol Cliente).
   */
  customerProfile?: (string | null) | Customer;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers".
 */
export interface Customer {
  id: string;
  linkedUser?: (string | null) | User;
  name: string;
  taxId?: string | null;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  contactName?: string | null;
  active?: boolean | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: string;
  code: string;
  name: string;
  description?: string | null;
  permissions?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  isActive?: boolean | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  code: string;
  name: string;
  parent?: (string | null) | Category;
  active?: boolean | null;
  description?: string | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories".
 */
export interface Subcategory {
  id: string;
  code: string;
  name: string;
  slug?: string | null;
  category: string | Category;
  description?: string | null;
  isActive?: boolean | null;
  sortOrder?: number | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units".
 */
export interface Unit {
  id: string;
  name: string;
  abbreviation: string;
  active?: boolean | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unit-equivalences".
 */
export interface UnitEquivalence {
  id: string;
  /**
   * Ej: 1 Caja = 12 Unidades
   */
  label: string;
  fromUnit: string | Unit;
  toUnit: string | Unit;
  /**
   * Cantidad de "unidad destino" que equivale a 1 "unidad origen".
   */
  factor: number;
  active?: boolean | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warehouses".
 */
export interface Warehouse {
  id: string;
  code: string;
  name: string;
  active?: boolean | null;
  address?: string | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections".
 */
export interface Section {
  id: string;
  warehouse: string | Warehouse;
  code: string;
  name: string;
  active?: boolean | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "racks".
 */
export interface Rack {
  id: string;
  section: string | Section;
  code: string;
  name: string;
  active?: boolean | null;
  notes?: string | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  code: string;
  barcode?: string | null;
  qrCode?: string | null;
  name: string;
  category?: (string | null) | Category;
  subcategory?: (string | null) | Subcategory;
  baseUnit: string | Unit;
  supplier?: (string | null) | Supplier;
  purchasePrice?: number | null;
  salePrice?: number | null;
  taxRate?: number | null;
  minStockBase?: number | null;
  trackInventory?: boolean | null;
  allowNegativeStock?: boolean | null;
  maxStockBase?: number | null;
  status?: ('active' | 'inactive' | 'discontinued') | null;
  active?: boolean | null;
  image?: (string | null) | Media;
  description?: string | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers".
 */
export interface Supplier {
  id: string;
  businessName: string;
  taxId: string;
  address?: string | null;
  phone?: string | null;
  email?: string | null;
  contactName?: string | null;
  active?: boolean | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-levels".
 */
export interface StockLevel {
  id: string;
  label: string;
  product: string | Product;
  rack: string | Rack;
  quantityBase: number;
  value: number;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-lots".
 */
export interface StockLot {
  id: string;
  label: string;
  product: string | Product;
  rack: string | Rack;
  receivedAt: string;
  initialQtyBase: number;
  qtyRemainingBase: number;
  unitCostBase: number;
  sourceMovement: string | StockMovement;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements".
 */
export interface StockMovement {
  id: string;
  label: string;
  movementType: 'in' | 'out' | 'adjust_in' | 'adjust_out';
  date: string;
  product: string | Product;
  rack: string | Rack;
  quantity: number;
  unit: string | Unit;
  unitCost?: number | null;
  createdBy?: (string | null) | User;
  notes?: string | null;
  quantityBase?: number | null;
  unitCostBase?: number | null;
  totalValue?: number | null;
  fifoAllocations?:
    | {
        lot: string | StockLot;
        qtyBase: number;
        unitCostBase: number;
        value: number;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kardex-entries".
 */
export interface KardexEntry {
  id: string;
  label?: string | null;
  product: string | Product;
  rack: string | Rack;
  movement: string | StockMovement;
  lot?: (string | null) | StockLot;
  entryType: 'in' | 'out';
  quantityBase: number;
  unitCostBase?: number | null;
  value?: number | null;
  balanceQtyBase: number;
  balanceValue: number;
  occurredAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchase-orders".
 */
export interface PurchaseOrder {
  id: string;
  orderNumber: string;
  supplier: string | Supplier;
  status: 'draft' | 'sent' | 'partial' | 'received' | 'invoiced' | 'cancelled';
  orderDate: string;
  receivedDate?: string | null;
  invoiceNumber?: string | null;
  items?:
    | {
        product: string | Product;
        quantity: number;
        unitCost: number;
        total?: number | null;
        id?: string | null;
      }[]
    | null;
  subtotal?: number | null;
  tax?: number | null;
  total?: number | null;
  notes?: string | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales-orders".
 */
export interface SalesOrder {
  id: string;
  orderNumber: string;
  customer?: (string | null) | Customer;
  status: 'draft' | 'confirmed' | 'delivered' | 'cancelled';
  saleDate: string;
  items?:
    | {
        product: string | Product;
        quantity: number;
        unitPrice: number;
        discount?: number | null;
        total?: number | null;
        id?: string | null;
      }[]
    | null;
  subtotal?: number | null;
  discountAmount?: number | null;
  tax?: number | null;
  total?: number | null;
  notes?: string | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs".
 */
export interface AuditLog {
  id: string;
  user?: (string | null) | User;
  action: string;
  module: string;
  resourceId?: string | null;
  details?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  ip?: string | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "returns".
 */
export interface Return {
  id: string;
  type: 'purchase' | 'sale';
  referenceType: 'purchase-order' | 'sales-order';
  referenceId: string;
  reason: string;
  status?: ('requested' | 'approved' | 'rejected' | 'processed') | null;
  items?:
    | {
        product: string | Product;
        quantity: number;
        unit: string | Unit;
        unitCost?: number | null;
        unitPrice?: number | null;
        lineTotal: number;
        id?: string | null;
      }[]
    | null;
  total?: number | null;
  createdBy?: (string | null) | User;
  approvedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  recipient: string | User;
  title: string;
  message: string;
  type?: ('info' | 'warning' | 'success' | 'error') | null;
  priority?: ('low' | 'medium' | 'high') | null;
  isRead?: boolean | null;
  entityType?: string | null;
  entityId?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  expiresAt?: string | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: string;
  key: string;
  value:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  scope: 'global' | 'warehouse' | 'role' | 'user';
  scopeId?: string | null;
  description?: string | null;
  updatedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'roles';
        value: string | Role;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'subcategories';
        value: string | Subcategory;
      } | null)
    | ({
        relationTo: 'units';
        value: string | Unit;
      } | null)
    | ({
        relationTo: 'unit-equivalences';
        value: string | UnitEquivalence;
      } | null)
    | ({
        relationTo: 'warehouses';
        value: string | Warehouse;
      } | null)
    | ({
        relationTo: 'sections';
        value: string | Section;
      } | null)
    | ({
        relationTo: 'racks';
        value: string | Rack;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'stock-levels';
        value: string | StockLevel;
      } | null)
    | ({
        relationTo: 'stock-lots';
        value: string | StockLot;
      } | null)
    | ({
        relationTo: 'stock-movements';
        value: string | StockMovement;
      } | null)
    | ({
        relationTo: 'kardex-entries';
        value: string | KardexEntry;
      } | null)
    | ({
        relationTo: 'suppliers';
        value: string | Supplier;
      } | null)
    | ({
        relationTo: 'customers';
        value: string | Customer;
      } | null)
    | ({
        relationTo: 'purchase-orders';
        value: string | PurchaseOrder;
      } | null)
    | ({
        relationTo: 'sales-orders';
        value: string | SalesOrder;
      } | null)
    | ({
        relationTo: 'audit-logs';
        value: string | AuditLog;
      } | null)
    | ({
        relationTo: 'returns';
        value: string | Return;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'settings';
        value: string | Setting;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  fullName?: T;
  status?: T;
  lastLoginAt?: T;
  customerProfile?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  description?: T;
  permissions?: T;
  isActive?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  parent?: T;
  active?: T;
  description?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subcategories_select".
 */
export interface SubcategoriesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  slug?: T;
  category?: T;
  description?: T;
  isActive?: T;
  sortOrder?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "units_select".
 */
export interface UnitsSelect<T extends boolean = true> {
  name?: T;
  abbreviation?: T;
  active?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "unit-equivalences_select".
 */
export interface UnitEquivalencesSelect<T extends boolean = true> {
  label?: T;
  fromUnit?: T;
  toUnit?: T;
  factor?: T;
  active?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warehouses_select".
 */
export interface WarehousesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  active?: T;
  address?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sections_select".
 */
export interface SectionsSelect<T extends boolean = true> {
  warehouse?: T;
  code?: T;
  name?: T;
  active?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "racks_select".
 */
export interface RacksSelect<T extends boolean = true> {
  section?: T;
  code?: T;
  name?: T;
  active?: T;
  notes?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  code?: T;
  barcode?: T;
  qrCode?: T;
  name?: T;
  category?: T;
  subcategory?: T;
  baseUnit?: T;
  supplier?: T;
  purchasePrice?: T;
  salePrice?: T;
  taxRate?: T;
  minStockBase?: T;
  trackInventory?: T;
  allowNegativeStock?: T;
  maxStockBase?: T;
  status?: T;
  active?: T;
  image?: T;
  description?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-levels_select".
 */
export interface StockLevelsSelect<T extends boolean = true> {
  label?: T;
  product?: T;
  rack?: T;
  quantityBase?: T;
  value?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-lots_select".
 */
export interface StockLotsSelect<T extends boolean = true> {
  label?: T;
  product?: T;
  rack?: T;
  receivedAt?: T;
  initialQtyBase?: T;
  qtyRemainingBase?: T;
  unitCostBase?: T;
  sourceMovement?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stock-movements_select".
 */
export interface StockMovementsSelect<T extends boolean = true> {
  label?: T;
  movementType?: T;
  date?: T;
  product?: T;
  rack?: T;
  quantity?: T;
  unit?: T;
  unitCost?: T;
  createdBy?: T;
  notes?: T;
  quantityBase?: T;
  unitCostBase?: T;
  totalValue?: T;
  fifoAllocations?:
    | T
    | {
        lot?: T;
        qtyBase?: T;
        unitCostBase?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kardex-entries_select".
 */
export interface KardexEntriesSelect<T extends boolean = true> {
  label?: T;
  product?: T;
  rack?: T;
  movement?: T;
  lot?: T;
  entryType?: T;
  quantityBase?: T;
  unitCostBase?: T;
  value?: T;
  balanceQtyBase?: T;
  balanceValue?: T;
  occurredAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suppliers_select".
 */
export interface SuppliersSelect<T extends boolean = true> {
  businessName?: T;
  taxId?: T;
  address?: T;
  phone?: T;
  email?: T;
  contactName?: T;
  active?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "customers_select".
 */
export interface CustomersSelect<T extends boolean = true> {
  linkedUser?: T;
  name?: T;
  taxId?: T;
  address?: T;
  phone?: T;
  email?: T;
  contactName?: T;
  active?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "purchase-orders_select".
 */
export interface PurchaseOrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  supplier?: T;
  status?: T;
  orderDate?: T;
  receivedDate?: T;
  invoiceNumber?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        unitCost?: T;
        total?: T;
        id?: T;
      };
  subtotal?: T;
  tax?: T;
  total?: T;
  notes?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sales-orders_select".
 */
export interface SalesOrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customer?: T;
  status?: T;
  saleDate?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        unitPrice?: T;
        discount?: T;
        total?: T;
        id?: T;
      };
  subtotal?: T;
  discountAmount?: T;
  tax?: T;
  total?: T;
  notes?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audit-logs_select".
 */
export interface AuditLogsSelect<T extends boolean = true> {
  user?: T;
  action?: T;
  module?: T;
  resourceId?: T;
  details?: T;
  ip?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "returns_select".
 */
export interface ReturnsSelect<T extends boolean = true> {
  type?: T;
  referenceType?: T;
  referenceId?: T;
  reason?: T;
  status?: T;
  items?:
    | T
    | {
        product?: T;
        quantity?: T;
        unit?: T;
        unitCost?: T;
        unitPrice?: T;
        lineTotal?: T;
        id?: T;
      };
  total?: T;
  createdBy?: T;
  approvedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  title?: T;
  message?: T;
  type?: T;
  priority?: T;
  isRead?: T;
  entityType?: T;
  entityId?: T;
  metadata?: T;
  expiresAt?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  key?: T;
  value?: T;
  scope?: T;
  scopeId?: T;
  description?: T;
  updatedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}